spring:
    application:
        name: jwt
    profiles:
        # application-KEY.yml 포함
        include: KEY

    # H2 Database 설정
    datasource:
        driver-class-name: org.h2.Driver
        url: 'jdbc:h2:mem:jwt'    # H2 DB 연결 주소 (In-Memory Mode)

    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    # H2 Console 설정
    h2:
        console: # H2 DB를 웹에서 관리할 수 있는 기능
            enabled: true           # H2 Console 사용 여부
            path: /h2-console       # H2 Console 접속 주소

    # JPA 설정
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true      # 쿼리 로그 포맷 (정렬)
                show_sql: true        # 쿼리 로그 출력

# Swagger
springdoc:
    api-docs:
        path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
        operations-sorter: alpha
        tags-sorter: alpha
        path: /jwt/swagger.html
        disable-swagger-default-url: true
        doc-expansion: none